"""add multi-tenancy: organizations and users

Revision ID: 3242d1056a1d
Revises: 0005
Create Date: 2026-03-02 00:57:10.448725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3242d1056a1d'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_340b_eligible', sa.Boolean(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('contract_pharmacy_ids', sa.JSON(), nullable=False),
    sa.Column('primary_contact_email', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_index('ix_diagnoses_name', table_name='diagnoses')
    op.drop_index('ix_goodrx_expires_at', table_name='goodrx_prices')
    op.drop_index('ix_goodrx_medication_id', table_name='goodrx_prices')
    op.drop_index('idx_medications_brand_names_text', table_name='medications', postgresql_using='gin')
    op.drop_index('idx_medications_category', table_name='medications')
    op.drop_index('idx_medications_equiv_group', table_name='medications', postgresql_where='(clinical_equivalence_group IS NOT NULL)')
    op.drop_index('idx_medications_generic_gin', table_name='medications', postgresql_using='gin')
    op.drop_index('idx_medications_name_gin', table_name='medications', postgresql_using='gin')
    op.drop_index('idx_medications_specialty_setting', table_name='medications')
    op.drop_index('idx_medications_therapeutic_class', table_name='medications')
    op.drop_index('idx_medications_tier_name', table_name='medications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_medications_tier_name', 'medications', ['formulary_tier', 'name'], unique=False)
    op.create_index('idx_medications_therapeutic_class', 'medications', ['therapeutic_class'], unique=False)
    op.create_index('idx_medications_specialty_setting', 'medications', ['specialty', 'setting'], unique=False)
    op.create_index('idx_medications_name_gin', 'medications', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_medications_generic_gin', 'medications', ['generic_name'], unique=False, postgresql_using='gin')
    op.create_index('idx_medications_equiv_group', 'medications', ['clinical_equivalence_group'], unique=False, postgresql_where='(clinical_equivalence_group IS NOT NULL)')
    op.create_index('idx_medications_category', 'medications', ['category'], unique=False)
    op.create_index('idx_medications_brand_names_text', 'medications', [sa.text('lower(brand_names::text)')], unique=False, postgresql_using='gin')
    op.create_index('ix_goodrx_medication_id', 'goodrx_prices', ['medication_id'], unique=False)
    op.create_index('ix_goodrx_expires_at', 'goodrx_prices', ['expires_at'], unique=False)
    op.create_index('ix_diagnoses_name', 'diagnoses', ['name'], unique=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
