"""add 340b models: contracts, dispensing, replenishment

Revision ID: add2781bc610
Revises: 3242d1056a1d
Create Date: 2026-03-02 01:01:22.874054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'add2781bc610'
down_revision: Union[str, None] = '3242d1056a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts_340b',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('vendor_portal_url', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('covered_medication_ndcs', sa.JSON(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_340b_is_active'), 'contracts_340b', ['is_active'], unique=False)
    op.create_index(op.f('ix_contracts_340b_organization_id'), 'contracts_340b', ['organization_id'], unique=False)
    op.create_table('replenishment_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'SUBMITTED', 'CANCELLED', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('cutoff_time', sa.DateTime(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('estimated_340b_savings_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('modification_history', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_orders_order_date'), 'replenishment_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_replenishment_orders_organization_id'), 'replenishment_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_replenishment_orders_status'), 'replenishment_orders', ['status'], unique=False)
    op.create_table('dispensing_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=True),
    sa.Column('ndc_code', sa.String(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('is_340b_eligible', sa.Boolean(), nullable=False),
    sa.Column('contract_340b_id', sa.String(), nullable=True),
    sa.Column('acquisition_cost', sa.Float(), nullable=True),
    sa.Column('patient_type', sa.String(), nullable=True),
    sa.Column('imported_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_340b_id'], ['contracts_340b.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispensing_records_contract_340b_id'), 'dispensing_records', ['contract_340b_id'], unique=False)
    op.create_index(op.f('ix_dispensing_records_dispensed_at'), 'dispensing_records', ['dispensed_at'], unique=False)
    op.create_index(op.f('ix_dispensing_records_is_340b_eligible'), 'dispensing_records', ['is_340b_eligible'], unique=False)
    op.create_index(op.f('ix_dispensing_records_medication_id'), 'dispensing_records', ['medication_id'], unique=False)
    op.create_index(op.f('ix_dispensing_records_ndc_code'), 'dispensing_records', ['ndc_code'], unique=False)
    op.create_index(op.f('ix_dispensing_records_organization_id'), 'dispensing_records', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispensing_records_organization_id'), table_name='dispensing_records')
    op.drop_index(op.f('ix_dispensing_records_ndc_code'), table_name='dispensing_records')
    op.drop_index(op.f('ix_dispensing_records_medication_id'), table_name='dispensing_records')
    op.drop_index(op.f('ix_dispensing_records_is_340b_eligible'), table_name='dispensing_records')
    op.drop_index(op.f('ix_dispensing_records_dispensed_at'), table_name='dispensing_records')
    op.drop_index(op.f('ix_dispensing_records_contract_340b_id'), table_name='dispensing_records')
    op.drop_table('dispensing_records')
    op.drop_index(op.f('ix_replenishment_orders_status'), table_name='replenishment_orders')
    op.drop_index(op.f('ix_replenishment_orders_organization_id'), table_name='replenishment_orders')
    op.drop_index(op.f('ix_replenishment_orders_order_date'), table_name='replenishment_orders')
    op.drop_table('replenishment_orders')
    op.drop_index(op.f('ix_contracts_340b_organization_id'), table_name='contracts_340b')
    op.drop_index(op.f('ix_contracts_340b_is_active'), table_name='contracts_340b')
    op.drop_table('contracts_340b')
    # ### end Alembic commands ###
